### ISSUE TITLE
Support for terraform modules in the TF files

### ISSUE THREAD

**Issue by lbustelo** [Bjorn248/terraform_cashier#7]
Let me start by saying that I may be doing something wrong here. Does `terraform_cashier` support infra defined within modules?

My terraform files rely heavily on calling out to `modules`. I did a `plan` to create the plan file and can see on the console output that terraform lists several resources to create. Most importantly, this includes an `aws_instance` that is actually defined within the `module`.

When I run the `terraform_cashier` on the plan file, it seems to not detect the `aws_instance`.

Note: this contain some extra debug prints I added.
```
read in resourceType:  aws_iam_role_policy
resource type not recognized:  aws_iam_role_policy
read in resourceType:  aws_iam_role
resource type not recognized:  aws_iam_role
read in resourceType:  aws_dynamodb_table
resource type not recognized:  aws_dynamodb_table
read in resourceType:  aws_iam_instance_profile
resource type not recognized:  aws_iam_instance_profile
Calling GraphQL Pricing API...

Cost of RDS
Breakdown by type:
Total Hourly: $0
Total Monthly: $0
Note: Monthly cost based on 730 runtime hours per month

Cost of EC2
Breakdown by type:
Total Hourly: $0
Total Monthly: $0
Note: Monthly cost based on 730 runtime hours per month

Total Monthly Cost of All Services: 0

**Comment by Bjorn248** [comment]
Hi @lbustelo, make sure you are planning from a blank state, otherwise it might not write your instances to the plan file. 

That being said, you might actually be onto something as I wrote this without modules in mind. Would it be possible to attach a sample plan file so that I can parse it and see if it differs from the plan files I generated during my testing? I have a feeling that https://github.com/Bjorn248/terraform_cashier/blob/master/main.go#L213 is the offending line, but I would need a plan file generated using modules to confirm that suspicion.

**Comment by lbustelo** [comment]
@Bjorn248 I have a fix... I can put a PR for it.

**Comment by Bjorn248** [comment]
@lbustelo hopefully it works now! I don't have a plan file that was generated from modules to test, so let me know.

**Comment by lbustelo** [comment]
@Bjorn248 It works... I'm using it now in my workflow. I'll continue to dig through the code to see if there are any other enhancements I can contribute back. This is very nice piece of work!
